# Generated by Django 5.1.6 on 2025-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("task", models.TextField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In progress", "In Progress"),
                            ("Done", "Done"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
