# Generated by Django 5.1.6 on 2025-03-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
