# Generated by Django 5.1.6 on 2025-03-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="username",
        ),
    ]
